<form method="post">
    <div>
        <label>
            First name:
            <input type="text" name="firstName" value="<?= $this->post['firstName'] ?>">
        </label>
    </div>
    <div>
        <label>
            Last name:
            <input type="text" name="lastName" value="<?= $this->post['lastName'] ?>">
        </label>
    </div>
    <br>
    <div>
        <button class="btn btn-primary">Submit</button>
    </div>
</form>
