<?php
/** @var \Application\Model\Author $author */

?>

<div>
    <a href="<?= $this->url('mvc', array('controller' => 'authors', 'action' => 'add')); ?>" class="btn btn-primary">
        Add new author
    </a>
</div>
<br>
<table class="table">
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Options</th>
    </tr>
    <?php foreach ($this->authors as $author): ?>
        <?php
        $editUrl = $this->url('mvc', ['action' => 'edit', 'id' => $author->getId()], true);
        $deleteUrl = $this->url('mvc', ['action' => 'delete', 'id' => $author->getId()], true);

        ?>
        <tr>
            <td><?= $author->getFirstName() ?></td>
            <td><?= $author->getLastName() ?></td>
            <td>
                <a href="<?= $editUrl ?>"><span class="btn-xs btn-primary glyphicon glyphicon-pencil"></span></a>
                <a href="<?= $deleteUrl ?>"><span class="btn-xs btn-primary glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

