<?php
$booksUrl = $this->url('mvc', ['controller' => 'index', 'action' => 'index']);
$authorsUrl = $this->url('mvc', ['controller' => 'authors', 'action' => 'index']);
$publishersUrl = $this->url('mvc', ['controller' => 'publishers', 'action' => 'index']);
?>


<html>
    <head>
        <title>SlimMVC</title>
        <link rel="stylesheet" href="/assets/css/reset.css">
        <link rel="stylesheet" href="/assets/css/style.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <ul class="nav nav-tabs">
                <li role="presentation"><a href="<?= $booksUrl ?>">Books</a></li>
                <li role="presentation"><a href="<?= $authorsUrl ?>">Authors</a></li>
                <li role="presentation"><a href="<?= $publishersUrl ?>">Publisher</a></li>
            </ul>
            <br>
            <?= $this->content ?>
        </div>
    </body>
</html>
