<?php
/** @var \Application\Model\Publisher $publisher */
?>

<div>
    <a href="<?= $this->url('mvc', array('controller' => 'publishers', 'action' => 'add')); ?>" class="btn btn-primary">
        Add new publisher
    </a>
</div>
<br>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Options</th>
    </tr>
    <?php foreach ($this->publishers as $publisher): ?>
        <?php
        $editUrl = $this->url('mvc', ['action' => 'edit', 'id' => $publisher->getId()], true);
        $deleteUrl = $this->url('mvc', ['action' => 'delete', 'id' => $publisher->getId()], true);

        ?>
        <tr>
            <td><?= $publisher->getName() ?></td>
            <td>
                <a href="<?= $editUrl ?>"><span class="btn-xs btn-primary glyphicon glyphicon-pencil"></span></a>
                <a href="<?= $deleteUrl ?>"><span class="btn-xs btn-primary glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

