<?php
/** @var \Application\Model\Publisher $publisher */
/** @var \Application\Model\Author $author */
?>
<form method="post">
    <div>
        <label>
            Title:
            <input type="text" name="title" value="<?= $this->post['title'] ?>">
        </label>
    </div>
    <div>
        <label>
            ISBN:
            <input type="text" name="isbn" value="<?= $this->post['isbn'] ?>">
        </label>
    </div>
    <div>
        <label>
            Publisher:
            <select name="publisherId">
                <?php foreach ($this->publishers as $publisher): ?>
                    <?php if ($this->post['publisherId'] === $publisher->getId()): ?>
                        <option value="<?= $publisher->getId() ?>" selected><?= $publisher->getName() ?></option>
                    <?php else: ?>
                        <option value="<?= $publisher->getId() ?>"><?= $publisher->getName() ?></option>
                    <?php endif ?>
                <?php endforeach ?>
            </select>
        </label>
    </div>
    <div>
        <label>
            Author:
            <select name="authorId">
                <?php foreach ($this->authors as $author): ?>
                    <?php if ($this->post['authorId'] === $author->getId()): ?>
                        <option value="<?= $author->getId() ?>" selected><?= $author ?></option>
                    <?php else: ?>
                        <option value="<?= $author->getId() ?>"><?= $author ?></option>
                    <?php endif ?>
                <?php endforeach ?>
            </select>
        </label>
    </div>
    <br>

    <div>
        <button class="btn btn-primary">Submit</button>
    </div>
</form>
